### PR TITLE
fix: change rule to warning instead of error

### PR DESCRIPTION
**Pull request by hellatan**

### CODE REVIEW

**Comment by hellatan** [comment]
i'm going to merge to downgrade this rule so it doesn't stop builds cc @twhid @robrichard @kostasmanionis

**Comment by hellatan** [comment]
published `eslint-config-1stdibs@4.5.2`

**Comment by twhid** [comment]
@hellatan now it will break locally but not on the jenkins, correct?

**Comment by hellatan** [comment]
@twhid that is correct...should have been caught in the original PR 

https://github.com/1stdibs/eslint-config-1stdibs/pull/42 🤦‍♂️ 

screen shot 2018-10-02 at 12 59 03 pm

**Pull request merged**
