### PR TITLE
Add no-dupe-keys rule

### PR DESCRIPTION
**Pull request by kostasmanionis**
For these cases 
screen shot 2017-01-13 at 11 59 25

http://eslint.org/docs/rules/no-dupe-keys

@1stdibs/srfe

### CODE REVIEW

**Comment by gedas-monginas** [comment]
👍

**Comment by twhid** [comment]
👍

**Comment by twhid** [comment]
+ @1stdibs/srfe

**Comment by lilianammmatos** [comment]
:1st_place_medal:

**Comment by twhid** [comment]
We have consensus on this? Seems like a no-brainer to me as it's almost certainly a mistake.

**Comment by kostasmanionis** [comment]
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Pull request merged**
