### PR TITLE
Add rule to enforce the use of relative paths in require statements

### PR DESCRIPTION
**Pull request by lilianammmatos**
Related PR: https://github.com/1stdibs/dibslint/pull/9

### CODE REVIEW

**Comment by lilianammmatos** [comment]
cc @twhid

**Comment by hellatan** [comment]
same q - will this only affect files that someone is trying to check-in?

**Comment by twhid** [comment]
My understanding is that we rely on the pre-commit hook to restrict linting to only files that one is trying to commit.

So, the answer is no, if one linted the entire codebase there's nothing in this PR to stop those files from failing on this rule.

**Comment by lilianammmatos** [comment]
Should I add that restriction? If someone lints the entire codebase it should not fail on this rule? I'm actually not sure how I would do that... Perhaps I could use different configs. One for pre-commit hook that includes this rule and another config for everything else that does not include this rule?

**Comment by hellatan** [comment]
isn't there a devbox/local and server config for this? @robrichard @jrdrg

**Comment by robrichard** [comment]
We use warnings vs errors. Only errors fail builds, but warnings fail the precommit hook

**Comment by lilianammmatos** [comment]
@hellatan this is ready to be merged, but merge https://github.com/1stdibs/dibslint/pull/9 first

**Comment by hellatan** [comment]
@robrichard @twhid i'm going to merge this if you guys don't object. I would say this is a minor version bump?

**Comment by twhid** [comment]
fine by me

**Comment by hellatan** [comment]
@lilianammmatos dibslint needs to go first, really? I would think it would be the other way around.

**Pull request merged**
