### PR TITLE
updated react rules

### PR DESCRIPTION
**Pull request by hellatan**
@1stdibs/srfe

- "react/jsx-closing-bracket-location": 1
- rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md

---
- "react/jsx-indent-props": 1
- rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent-props.md

---
- "react/prefer-es6-class": [1, "always"]
- rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-es6-class.md

---
- "react/prefer-stateless-function": 1
- rule: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md

### CODE REVIEW

**Comment by jrdrg** [comment]
Not really keen on the first two rules, as I personally don't use that indent style, but if everyone else is ok with enforcing that across all projects then I guess that's fine. 👍 to the last two, though

**Comment by hellatan** [comment]
updated without the space - @1stdibs/srfe

**Comment by gedas-monginas** [comment]
I'm 👌 with these rules

**Comment by nitruxa** [comment]
:shipit:

**Comment by hellatan** [comment]
anyone else? I think we should have the indenting as I've seen (and been a culprit of) having varying styles of indenting a react component:

```jsx
<Component propYes
           hasProp={false}
           prop2="sure"
           prop3="nope" />
/////////
<Component 
    propYes
    hasProp={false}
    prop2="sure"
    prop3="nope" />
/////////
<Component propYes
    hasProp={false}
    prop2="sure"
    prop3="nope" />
/// etc
```
this would be the way for indenting:
```jsx
<Component 
    propYes
    hasProp={false}
    prop2="sure"
    prop3="nope" 
/>
```

I'm going to merge this soon as no one else seems to have an opinion and @jrdrg you seem to be in the minority in this indenting config (@robrichard is also for this one as we've discussed this offline).

**Comment by jrdrg** [comment]
Sure, that's fine, if everyone else agrees

**Comment by brettjashford** [comment]
👍 

re: indenting, i've always done it that way, but haven't policed it in PRs

**Pull request merged**
