### PR TITLE
made no-multi-spaces and key-spacing throw an error when violated. set key-spacing.afterColon to true and key-spacing.mode to strict

### PR DESCRIPTION
**Pull request by antialias**
Re: https://github.com/1stdibs/1stdibs.com/pull/3802#discussion_r43958238

http://eslint.org/docs/rules/no-multi-spaces.html
http://eslint.org/docs/rules/key-spacing.html

### CODE REVIEW

**Comment by antialias** [comment]
@hellatan @prestifidibs @brettjashford @robrichard @nameofname @jrdrg

**Comment by prestifidibs** [comment]
:+1:

**Comment by hellatan** [comment]
will this throw an error when you have something like this:

```js
const foo            = "bar";
const someOtherConst = "some other value";
```

**Comment by antialias** [comment]
yes, that will be caught by [`no-multi-spaces`](http://eslint.org/docs/rules/no-multi-spaces.html)

**Comment by hellatan** [comment]
i'm a :-1: on that one then. I honestly think it makes it easier to read when have a large stack of vars and the equal signs line up. If people feel strongly that that shouldn't be allowed, then i won't fight it, but I think either way is both opinionated. 

Plus, we're talking about whitespace (again) which I think is kind of a waste of time since it's not focusing on the logic of the code itself.

**Comment by hellatan** [comment]
also, i don't think having this whitespace should fail builds.

**Comment by jrdrg** [comment]
I agree with @hellatan here, sometimes I think aligned `=` or `:` makes the code easier to read, especially in the case of long lists of variables or object properties.

**Comment by jrdrg** [comment]
Plus, if you use phpstorm it's super easy to do this alignment automatically if you set it up in the auto-format settings. Sublime has an alignment plugin to also do the same thing.

**Comment by hellatan** [comment]
also @gedas-monginas @nitruxa

**Comment by twhid** [comment]
If we're going to do this it needs to be reproducible in our auto-formatting. We need the auto-formatter in phpstorm (at the very least) be able to format code so that it will pass the lint rule. If it can't, then this is a waste of time.

**Comment by brettjashford** [comment]
i'm :+1: on this. i don't like seeing unnecessary whitespace changes in diffs and i don't feel that assignment statements are difficult to read as they are.

**Comment by jrdrg** [comment]
With regards to whitespace changes in diffs, apparently you can filter that out in github by appending `?w=1` to the url:

https://github.com/blog/967-github-secrets

**Comment by twhid** [comment]
I'm :-1: until someone can answer whether we can match these rules with auto-formatting.

**Comment by hellatan** [comment]
@jrdrg ya, but you can't comment in that view :confused:

**Comment by antialias** [comment]
Regarding whitespace, I'm more concerned with standardizing on rules than the rule that we end up with. Consider the following example:
Original code:
```js
hello = require('world');
foo = require('bar');
```
then someone changes it to:
```js
hello = require('world');
foo =   require('bar'); // spaces added
```
then in another commit, someone else changes it back to because they prefer that style:
```js
hello = require('world');
foo = require('bar'); // spaces removed
```
There's no meaningful change here, and if eslint enforced a standard, then these two meaningless changes wouldn't have been committed in the first place, saving everyone's time during code review. I have seen this pattern show up many times while reviewing code and it feels like we're stuck in an endless loop of personal whitespace opinions. I'd like to put a stop to it.

Similar to my argument above about using a whitespace rule, my preference is to use the rule that minimises unnecessary changes and makes it easiest to see which line actually changed. For example, consider the below diffs. Which of one most clearly shows the line that changed?

whitespace alignment maintained ([actual commit](https://github.com/antialias/whitespacedemo/commit/448c332423ac0a45bdf489e239a97e05e33174f9)):
screen shot 2015-11-16 at 12 15 04 pm
no-multi-spaces ([actual commit](https://github.com/antialias/whitespacedemo/commit/822685a1049a7c8c6f3f1e05d98835abb09bb0c8)):
screen shot 2015-11-16 at 12 14 36 pm

**Comment by antialias** [comment]
@twhid, re: auto-formatting, eslint has an option (`--fix`) to fix code in violation of rules. I just ran it on .com and the changes look fine. I don't think that any auto-formatting would be necessary to prohibit multiple spaces going forward. Have a look at the diff: https://github.com/antialias/1stdibs.com/commit/cbf3f8c8b236357336b421056c79e6165ddf46b9
(if you [add ?w=1 to hide whitespace](https://github.com/antialias/1stdibs.com/commit/cbf3f8c8b236357336b421056c79e6165ddf46b9?w=1), the diff becomes empty)

**Comment by nitruxa** [comment]
@antialias :+1: for `no-multi-spaces` b/c of cleaner diffs

**Comment by robrichard** [comment]
I'm :+1: too, + having eslint auto fix it

**Comment by jrdrg** [comment]
I'm fine with this as long as it's automatic, if someone (like me) likes to auto-format, eslint can just fix the whitespace after I commit and it will all be ok =)

**Comment by hellatan** [comment]
if it's as simple as `--fix`, then :+1: and then yes, the autoformatting wouldn't be an issue.

**Comment by twhid** [comment]
OK, I'm sold +1.

**Comment by twhid** [comment]
so do we need a pr to add --fix to dibslint or does it get added to the
scripts in each repo?

**Comment by antialias** [comment]
I think we should be judicious about making `--fix` the default on dibslint, but it would be nice to have as a option, and even nicer if it could somehow be passed through the `git commit`.
I'm not ready to loose that much control over the code that I'm committing.

**Comment by twhid** [comment]
speak now or hold your peas... gonna merge this... :100:

**Pull request merged**
