### PR TITLE
turn comma-spacing and key-spacing rules back on

### PR DESCRIPTION
**Pull request by hellatan**
@1stdibs/srfe another one - i didn't want to have one block the other

- http://eslint.org/docs/rules/comma-spacing
- http://eslint.org/docs/rules/key-spacing

### CODE REVIEW

**Comment by gedas-monginas** [comment]
👍

**Comment by nitruxa** [comment]
🚢

**Comment by hellatan** [comment]
@1stdibs/srfe gonna merge this soon as well. The `key-spacing` rule prevents this:
```js
const obj = {
    key    : 1,
    another: true
}
```
and requires one to do this:
```js
const obj = {
    key: 1,
    another: true
}
```
comma-spacing is to make sure there is no space before a comma and one space after the comma:
```js
const arr = [1,2] // <= wrong
const arr = [1 ,2] // <= wrong
///
const arr = [1, 2] //< = correct
```

**Comment by brettjashford** [comment]
👍 

agreed, not a fan of people lining up their values in objects, causes unnecessary diff noise when someone adds a longer key.

**Comment by hellatan** [comment]
i actually do like the alignment, but ya, the unnecessary diffs is annoying. merging.

**Pull request merged**
