### PR TITLE
setting require-path-exists as a peerdep

### PR DESCRIPTION
**Pull request by antialias**

### CODE REVIEW

**Comment by lilianammmatos** [comment]
@antialias pls bump version and publish the version of this package! thx.

**Comment by antialias** [comment]
@lilianammmatos I'm getting `you do not have permission to publish "eslint-config-1stdibs"` when I attempt to publish. Probably because it's a public npm package. I've already pushed the version change and tag to github; can you `git pull origin master && npm publish`?

**Comment by lilianammmatos** [comment]
```
liliana at Liliana-2 in ~/projects/eslint-config-1stdibs on master
$ npm publish
+ eslint-config-1stdibs@3.0.4
```

**Comment by antialias** [comment]
awesome, thanks.

**Pull request merged**
